---
  - name: GIT | Install modern git ppa repo
    apt_repository: repo='ppa:git-core/ppa'
    become: yes
    tags:
      - git

  - name: GIT | Install package
    apt: pkg="git" state="present"
    become: yes
    retries: 3
    register: git_result
    until: not git_result.failed
    tags:
      - git
